### ISSUE TITLE
Building error /bin/sh: /build/source/scripts/autogen-type-erased: not found on Nix(Sandboxing mode)

### ISSUE THREAD

**Issue by GTrunSec** [zeek/spicy#393]
Does anyone pass the spicy with flatpack ?
you can find the full log of zeek with spicy build process at here [Nix HydraCI](http://221.4.35.244:8300/build/89/nixlog/2)
Summary details:
```
====================|  Spicy Build Summary  |====================

Version:                ()

Build type:            RelWithDebInfo
Build directory:       /build/spicy/build
Install prefix:        /usr/local
Build shared libs:     yes

Host system:           Linux 4.19.0-9-amd64 (x86_64)
C compiler:            /nix/store/fb30zc52va0g99q8qgv7kx4ngq163pii-gcc-wrapper-9.3.0/bin/gcc (GNU 9.3.0)
C++ compiler:          /nix/store/fb30zc52va0g99q8qgv7kx4ngq163pii-gcc-wrapper-9.3.0/bin/g++ (GNU 9.3.0)

JIT enabled:           yes
Zeek plugin enabled:   yes
Zeek JIT enabled:      yes

Use ccache:            yes
Use gold linker:       yes
Use sanitizers:        no
Use backtrace:         yes

Clang/LLVM found:      yes
Clang version:         9.0.1
LLVM version:          7.1.0
LLVM prefix:           /nix/store/192bj4v4bp7fy192scgw78zdly82mik7-llvm-7.1.0
Clang prefix:          /nix/store/p7q2j9alkjmfq0kj5wikz0x1irq908fq-clang-9.0.1
Clang executable:      /nix/store/p7q2j9alkjmfq0kj5wikz0x1irq908fq-clang-9.0.1/bin/clang++
Clang resource dir:    /nix/store/p7q2j9alkjmfq0kj5wikz0x1irq908fq-clang-9.0.1/lib/clang/9.0.1
C sys include dirs:
C++ sys include dirs:
Clang gcc tolchain:    n/a
Warnings are errors:   false

Zeek found:            yes
Zeek version:          3.0.7
Zeek debug build:      no
Zeek root dir:         /nix/store/wn4fghgigpvgy4piwpsw0vkbvckhv3j1-zeek-3.0.7

Bison version:         3.5.4
CMake version:         3.17.2
Flex version:          2.6.4
Python version:        3.8.2
zlib version:          1.2.11
```
Building process error output:
```
[103/268] Generating include/hilti/autogen/__node.hecl.6.4/src/rt/types/address.cc.o
FAILED: hilti/include/hilti/autogen/__node.h
cd /build/spicy/build/hilti && /build/spicy/scripts/autogen-type-erased --output /build/spicy/build/hilti/include/hilti/autogen/__node.h /build/spicy/hilti/include/hilti/ast/node.api
/bin/sh: /build/spicy/scripts/autogen-type-erased: not found
[104/268] Generating include/hilti/autogen/__ctor.h
FAILED: hilti/include/hilti/autogen/__ctor.h
cd /build/spicy/build/hilti && /build/spicy/scripts/autogen-type-erased --constant --output /build/spicy/build/hilti/include/hilti/autogen/__ctor.h /build/spicy/hilti/include/hilti/ast/ctor.api
/bin/sh: /build/spicy/scripts/autogen-type-erased: not found
[105/268] Generating include/hilti/autogen/__declaration.h
FAILED: hilti/include/hilti/autogen/__declaration.h
cd /build/spicy/build/hilti && /build/spicy/scripts/autogen-type-erased --constant --output /build/spicy/build/hilti/include/hilti/autogen/__declaration.h /build/spicy/hilti/include/hilti/ast/declaration.api
/bin/sh: /build/spicy/scripts/autogen-type-erased: not found
[106/268] Generating include/hilti/autogen/__expression.h
FAILED: hilti/include/hilti/autogen/__expression.h
cd /build/spicy/build/hilti && /build/spicy/scripts/autogen-type-erased --constant --output /build/spicy/build/hilti/include/hilti/autogen/__expression.h /build/spicy/hilti/include/hilti/ast/expression.api
/bin/sh: /build/spicy/scripts/autogen-type-erased: not found
[107/268] Generating include/hilti/autogen/__resolved-operator.h
FAILED: hilti/include/hilti/autogen/__resolved-operator.h
cd /build/spicy/build/hilti && /build/spicy/scripts/autogen-type-erased --constant --output /build/spicy/build/hilti/include/hilti/autogen/__resolved-operator.h /build/spicy/hilti/include/hilti/ast/expressions/resolved-operator.api
/bin/sh: /build/spicy/scripts/autogen-type-erased: not found
[108/268] Generating include/hilti/autogen/__operator.h
FAILED: hilti/include/hilti/autogen/__operator.h
cd /build/spicy/build/hilti && /build/spicy/scripts/autogen-type-erased --constant --output /build/spicy/build/hilti/include/hilti/autogen/__operator.h /build/spicy/hilti/include/hilti/ast/operator.api
/bin/sh: /build/spicy/scripts/autogen-type-erased: not found
[109/268] Generating include/hilti/autogen/__statement.h
FAILED: hilti/include/hilti/autogen/__statement.h
cd /build/spicy/build/hilti && /build/spicy/scripts/autogen-type-erased --constant --output /build/spicy/build/hilti/include/hilti/autogen/__statement.h /build/spicy/hilti/include/hilti/ast/statement.api
/bin/sh: /build/spicy/scripts/autogen-type-erased: not found
[110/268] Generating include/hilti/autogen/__type.h
```

**Comment by bbannier** [comment]
Thanks for filing this issue @GTrunSec. We do not test building with Nix upstream so there are likely issues. A couple things to keep in mind
- Spicy can currently only build in a git checkout with some history (maxdepth=1 clones are insufficient); this should fix the `fatal: not a git repository (or any of the parent directories): .git` errors you are seeing.
- the build requires access to the `scripts/` folder at the root of the project (the error you are seeing here); I am not exactly sure how you organize you source and build directories, but I would suggest you to if possible build in the source tree in a directory name `build/` (this is what we test in CI).
- Spicy uses shared libraries so building with support for that seems to be a good first approach.

For inspiration on how to configure the project have a look at how `./configure` sets up the project for CMake.

**Comment by JustinAzoff** [comment]
try  this

```
pkgs.llvmPackages_10.stdenv.mkDerivation {
  pname = "spicy";
  version = "latest";
  src = ./.;
  nativeBuildInputs = with pkgs; [ gcc git cmake flex bison bash python37 which];
  buildInputs = with pkgs; [ zlib python37 llvm_10 clang_10 gcc ];

  preConfigure = ''
    patchShebangs ./scripts/autogen-type-erased
    patchShebangs ./scripts/autogen-dispatchers
  '';

  #doCheck = true;
  #patches = pkgs.stdenv.cc.isClang;
  #cmakeFlags = [ "-DCMAKE_SKIP_BUILD_RPATH=OFF"] ;
  cmakeFlags = [ "-DHILTI_USE_JIT=ON" ];
}
```

**Comment by JustinAzoff** [comment]
This gets it further, but still fails:

```
  preConfigure = ''
    patchShebangs ./scripts/autogen-type-erased
    patchShebangs ./scripts/autogen-dispatchers
    patchShebangs ./configure
    ./configure --prefix=$out --build-type=Release
  '';
```

nix-build is detecting that it is a cmake project and skipping ./configure, which screws things up a bit.  forcing it to run configure makes it a bit better.

With JIT off via `cmakeFlags = [ "-DHILTI_HAVE_JIT=OFF"] ;` it builds but fails to run due to `hilti::JIT::initRuntime()` being missing.

```
$ ./result/bin/spicy-driver
./result/bin/spicy-driver: symbol lookup error: /nix/store/113dzsmd72p0d6683z7r5a0j49jinj5x-spicy-latest/bin/../lib/libhilti.so: undefined symbol: _ZN5hilti3JIT11initRuntimeEv
```

With it on it fails with

```
/build/spicy/hilti/src/compiler/clang.cc:36:10: fatal error: 'clang/Basic/Version.h' file not found
```

which is something  off with the build environment or with the clang wrapper, maybe @GTrunSec knows what.

**Comment by GTrunSec** [comment]
first of all, thanks for @JustinAzoff  the response to help me debug this issue with nix and @bbannier your answer. it has been fixed by https://github.com/hardenedlinux/nixpkgs-hardenedlinux/blob/master/test/spicy.nix 
Also, I'm trying to adapt the spicy plugin in Zeek installation(https://github.com/hardenedlinux/nixpkgs-hardenedlinux/blob/9adbf9e382adeadc4d7d30b67ef787d66e3a107b/pkgs/zeek/plugin.nix#L31)

- [Spicy hydraCI Building log](http://221.4.35.244:8300/build/93/nixlog/1/tail)
- [With zeek Building log](http://221.4.35.244:8300/build/94/nixlog/2/tail)
```
09:11:56 with debian in nixpkgs-hardenedlinux/test at gtcompile on  master [$] 
➜ ./result/bin/spicyc -help                    
Usage: spicyc [options] <inputs>

Options controlling code generation:

  -c | --output-c++               Print out all generated C++ code (including linker glue by default).
  -d | --debug                    Include debug instrumentation into generated code.
  -e | --output-all-dependencies  Output list of dependencies for all compiled modules.
  -l | --output-linker            Print out only generated HILTI linker glue code.
  -j | --jit-code                 Fully compile all code, and then execute it unless --output-to gives a file to store it
  -o | --output-to <path>         Path for saving output.
  -p | --output-hilti             Just output parsed HILTI code again.
  -v | --version                  Print version information.
  -A | --abort-on-exceptions      When executing compiled code, abort() instea
```

**Comment by GTrunSec** [comment]
- Summary details
```
====================|  Spicy Build Summary  |====================

Version:                ()

Build type:            RelWithDebInfo
Build directory:       /build/spicy/build
Install prefix:        /usr/local
Build shared libs:     yes

Host system:           Linux 4.19.0-9-amd64 (x86_64)
C compiler:            /nix/store/hjmar4rsywzx099qff3z84pi3smw9z7k-clang-wrapper-9.0.1/bin/clang (Clang 9.0.1)
C++ compiler:          /nix/store/hjmar4rsywzx099qff3z84pi3smw9z7k-clang-wrapper-9.0.1/bin/clang++ (Clang 9.0.1)

JIT enabled:           yes
Zeek plugin enabled:   yes
Zeek JIT enabled:      yes

Use ccache:            yes
Use gold linker:       yes
Use sanitizers:        no
Use backtrace:         yes

Clang/LLVM found:      yes
Clang version:         9.0.1
LLVM version:          9.0.1
LLVM prefix:           /nix/store/31461vrd0gycijw9z67337xcyjylw9vb-llvm-9.0.1
Clang prefix:          /nix/store/p7q2j9alkjmfq0kj5wikz0x1irq908fq-clang-9.0.1
Clang executable:      /nix/store/hjmar4rsywzx099qff3z84pi3smw9z7k-clang-wrapper-9.0.1/bin/clang++
Clang resource dir:    /nix/store/hjmar4rsywzx099qff3z84pi3smw9z7k-clang-wrapper-9.0.1/resource-root
C sys include dirs:
C++ sys include dirs:
Clang gcc tolchain:    n/a
Warnings are errors:   false

Zeek found:            yes
Zeek version:          3.0.7
Zeek debug build:      no
Zeek root dir:         /nix/store/fwikd9jsrldz8ar1dkgqn6zifp0ncpk3-zeek-3.0.7

Bison version:         3.5.4
CMake version:         3.17.2
Flex version:          2.6.4
Python version:        3.8.2
zlib version:          1.2.11

================================================================
```
- Install issue Spicy (with zeek)
```
-- Install configuration: "RelWithDebInfo"
Warning: //build/spicy/build/zeek/plugin/zeek-install-scratch does not exist; has Zeek been installed?
CMake Error at zeek/plugin/cmake_install.cmake:56 (file):
  file cannot create directory: /usr/local/lib64/spicy/Zeek_Spicy.  Maybe
  need administrative privileges.
Call Stack (most recent call first):
  zeek/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)


make[1]: *** [Makefile:94: install] Error 1
make[1]: Leaving directory '/build/spicy/build'
make: *** [Makefile:15: install] Error 2
/nix/store/snf5jcddm6plj2k0jissiap3lx9kcvrc-install_plugin: line 18: [: missing `]'
```

**Comment by GTrunSec** [comment]
I'm newbie for the Spicy. I can not do a pre-test such as hello.spicy. this problem has been mentioned here https://github.com/zeek/spicy/issues/400 (most like I need change the static lib to dynamic libs?)
@JustinAzoff  if you would like using my binary cache do a test quickly.
```
nix-build spicy --option substituters "http:224.4.35.247:5000" --option trusted-public-keys "http://221.4.35.247:x+xxTedX3AzLsLYJ86Xb7oTO8YuVT+ye3LSnJb6GfVg="

```
